"""init

Revision ID: 65edfb10281f
Revises: 
Create Date: 2025-03-20 19:10:57.192502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65edfb10281f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=False),
                    sa.Column('password', sa.String(length=512), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('bill',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('amount', sa.Numeric(), nullable=True),
                    sa.Column('account_id', sa.Integer(), nullable=True, comment='ID счета в сторонней платежной системе?'),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_bill_account_id'), 'bill', ['account_id'], unique=True)
    op.create_table('transaction',
                    sa.Column('t_amount', sa.Numeric(), nullable=False),
                    sa.Column('transaction_id', sa.String(), nullable=False),
                    sa.Column('bill_id', sa.INTEGER(), nullable=True),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('transaction_id'),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_bill_account_id'), table_name='bill')
    op.drop_table('bill')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
