version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile_inline: |
        FROM sanicframework/sanic:latest-py3.11

        ENV LC_ALL=C.UTF-8
        ENV LANG=C.UTF-8
        ENV LANGUAGE=C.UTF-8

        WORKDIR .

        COPY requirements.txt .

        RUN apk add --no-cache \
            gcc \
            musl-dev \
            libffi-dev \
            python3-dev \
            libpq-dev 

        RUN pip install --upgrade pip

        RUN pip install --no-cache-dir -r requirements.txt

        COPY app/ /app/
        COPY .env ./app/
        COPY tests/ /tests/

        ENV PYTHONPATH=/app
    volumes:
      - ./app:/app
    depends_on:
      - postgresql_pytest
    env_file:
      - .env 
    command: pytest tests/ -v
  postgresql_pytest:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${PYTEST_POSTGRES_DB}
      POSTGRES_USER: ${PYTEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PYTEST_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
