# docker-compose.yml
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python -m app.server
    env_file:
      - .env 
    volumes:
      - ./app:/app
    depends_on:
      - postgresql
    restart: always

  postgresql:
    image: postgres:13  
    restart: always
    container_name: web_psql
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data: